spring.application.name=backend

spring.datasource.url=jdbc:postgresql://metro.proxy.rlwy.net:43451/railway?sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.username=postgres
spring.datasource.password=qiGmvTvpaTyZQGWqSKOcbqUCimdcXqYU
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=10