name: CI Pipeline

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:

  backend:
    name: Build Backend (Spring Boot)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: |
          cd backend
          mvn clean install -DskipTests

  frontend:
    name: Build Frontend (React)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & Build
        run: |
          cd frontend
          npm install
          npm run build